// Data models shared by the whole app. Everything stored in Firestore is plain JSON
// (numbers, strings, booleans, arrays, objects, null) so it round-trips through export/import.

export type Units = 'lb' | 'kg';

/** ISO calendar date in local time, e.g. "2026-09-30". */
export type ISODate = string;

export const MUSCLE_GROUPS = [
  'back',
  'chest',
  'shoulders',
  'biceps',
  'triceps',
  'quads',
  'hamstrings',
  'glutes',
  'calves',
  'abs',
  'other',
] as const;
export type MuscleGroup = (typeof MUSCLE_GROUPS)[number];

export interface Exercise {
  /** Stable id: history and charts follow this, never the name. */
  id: string;
  name: string;
  muscleGroup: MuscleGroup;
  /** Weight means assistance (e.g. assisted pull-ups): lower is better. */
  assisted: boolean;
}

export type Target =
  | { kind: 'reps'; reps: number }
  | { kind: 'range'; min: number; max: number }
  | { kind: 'failure'; ceiling: number | null };

export interface BlockExercise {
  exerciseId: string;
  target: Target;
}

export interface WorkBlock {
  id: string;
  kind: 'work';
  /** Done in order each round. One exercise = normal sets; several = superset/circuit. */
  exercises: BlockExercise[];
  rounds: number;
  /** Rest after each round, in seconds (0 = none). */
  restSec: number;
}

export interface RestBlock {
  id: string;
  kind: 'rest';
  restSec: number;
}

export type Block = WorkBlock | RestBlock;

export interface WorkoutTemplate {
  id: string;
  name: string;
  blocks: Block[];
}

export const WEEKDAYS = ['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun'] as const;
export type Weekday = (typeof WEEKDAYS)[number];

/** Weekday → workout template id, or null for rest. */
export type Split = Record<Weekday, string | null>;

export interface Plan {
  exercises: Exercise[];
  workouts: WorkoutTemplate[];
  split: Split;
}

export interface SetResult {
  weight: number;
  reps: number;
  rpe: number | null;
}

export type StepStatus = 'pending' | 'logged' | 'log_later';

/** Exercise step with a snapshot of everything needed to display it, independent of the plan. */
export interface ExerciseStep {
  kind: 'exercise';
  id: string;
  blockIndex: number;
  round: number;
  rounds: number;
  /** Position within the block's exercise list, and its length (>1 = superset). */
  exerciseIndex: number;
  blockSize: number;
  exerciseId: string;
  exerciseName: string;
  muscleGroup: MuscleGroup;
  assisted: boolean;
  target: Target;
  status: StepStatus;
  result: SetResult | null;
}

export interface RestStep {
  kind: 'rest';
  id: string;
  blockIndex: number;
  restSec: number;
  /** True for a standalone rest block, false for rest after a round. */
  standalone: boolean;
}

export type Step = ExerciseStep | RestStep;

/** Timestamp-based rest timer. Remaining time is always computed from the clock. */
export interface RestTimer {
  durationMs: number;
  /** Epoch ms when the rest ends (while running). */
  endsAt: number;
  /** Set while paused: the remaining ms frozen at pause time. */
  pausedRemainingMs: number | null;
}

export type SessionStatus = 'in_progress' | 'completed';

export interface WorkoutSession {
  id: string;
  date: ISODate;
  workoutId: string | null;
  workoutName: string;
  status: SessionStatus;
  startedAt: number;
  endedAt: number | null;
  steps: Step[];
  /** Focus-mode cursor. Equal to steps.length when every step has been passed. */
  currentIndex: number;
  /** Running rest timer for the current rest step, if any. */
  timer: RestTimer | null;
  updatedAt: number;
  /** Generated by "Load sample data". */
  sample: boolean;
}

export interface DayEntry {
  date: ISODate;
  kcal: number | null;
  protein: number | null;
  fat: number | null;
  carbs: number | null;
  /** True when carbs were typed in; false = auto-calculated from remaining calories. */
  carbsManual: boolean;
  /** Morning bodyweight in the current units. */
  weight: number | null;
  updatedAt: number;
  sample: boolean;
}

export interface NutritionTargets {
  maintenanceKcal: number;
  kcalTarget: number;
  kcalMin: number;
  kcalMax: number;
  proteinMin: number;
  proteinMax: number;
  fatMin: number;
  fatMax: number;
}

export interface AdjustmentRule {
  /** Target weekly gain band, in current units per week. */
  gainMinPerWeek: number;
  gainMaxPerWeek: number;
  /** Suggested calorie change when outside the band. */
  kcalStepMin: number;
  kcalStepMax: number;
}

export interface TimerPrefs {
  defaultRestSec: number;
  weightStep: number;
  autoAdvance: boolean;
  sound: boolean;
}

export interface Settings {
  schemaVersion: 1;
  units: Units;
  nutrition: NutritionTargets;
  adjustment: AdjustmentRule;
  timer: TimerPrefs;
  plan: Plan;
  lastBackupAt: number | null;
  hasSampleData: boolean;
}

export interface ExportFile {
  app: 'gymplan';
  version: 1;
  exportedAt: number;
  settings: Settings;
  days: DayEntry[];
  sessions: WorkoutSession[];
}
